language: elixir
elixir:
  - '1.8.0'
otp_release:
  - '21.1.4'

services:
  - postgresql

install:
  - mix local.rebar --force
  - mix local.hex --force
  - make fetch_dependencies

before_script:
  - make migrate_ci

script:
  - make test_play
